(function(){
const header=document.getElementById('topbar'); const onScroll=()=>header&&header.classList.toggle('scrolled',scrollY>40); addEventListener('scroll',onScroll,{passive:true});onScroll();
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');if(toggle&&nav){toggle.onclick=()=>{const o=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',o)};nav.addEventListener('click',e=>{if(e.target.closest('a'))nav.classList.remove('open')})}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const gallery=document.querySelector('[data-gallery]');if(gallery){const step=()=>Math.min(gallery.clientWidth*.72,650);document.querySelector('[data-gallery-next]').onclick=()=>gallery.scrollBy({left:step(),behavior:'smooth'});document.querySelector('[data-gallery-prev]').onclick=()=>gallery.scrollBy({left:-step(),behavior:'smooth'})}
const media=[...document.querySelectorAll('.parallax-media')];let tick=false;function motion(){const vh=innerHeight;media.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom<0||r.top>vh)return;const p=((r.top+r.height/2)-vh/2)/vh;el.style.setProperty('--py',(p*-42)+'px')});tick=false}addEventListener('scroll',()=>{if(!tick&&!matchMedia('(prefers-reduced-motion: reduce)').matches){tick=true;requestAnimationFrame(motion)}},{passive:true});motion();
const upload=document.querySelector('input[type=file]'),label=document.querySelector('[data-upload-label]');if(upload&&label)upload.onchange=()=>label.textContent=upload.files.length?upload.files.length+' Bild(er) ausgewählt':'Noch keine Bilder ausgewählt';
document.querySelector('.contact-form')?.addEventListener('submit',e=>e.preventDefault());
})();
